# Generated by Django 4.2.13 on 2024-06-28 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spadeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplemodel',
            old_name='field',
            new_name='fieldSample',
        ),
    ]
