# Generated by Django 4.2.13 on 2024-06-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spadeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swe',
            name='time_end_obs',
            field=models.CharField(max_length=50, verbose_name='Time end observations'),
        ),
    ]
