# Generated by Django 4.2.13 on 2024-06-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spadeapp', '0002_alter_swe_time_end_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swe',
            name='region',
            field=models.CharField(max_length=20, verbose_name='Region'),
        ),
    ]
