# Generated by Django 4.2.13 on 2024-06-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spadeapp', '0002_rename_field_samplemodel_fieldsample'),
    ]

    operations = [
        migrations.CreateModel(
            name='TGF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TGF_name', models.CharField(max_length=30)),
                ('GEO_long', models.FloatField(verbose_name='geo_long')),
                ('GEO_lat', models.FloatField(verbose_name='geo_lat')),
                ('trigger_time', models.DateTimeField(verbose_name='trigger_time')),
                ('orbit', models.IntegerField(verbose_name='orbit')),
                ('T50', models.TimeField(verbose_name='T50')),
                ('T50_err', models.TimeField(verbose_name='T50_err')),
                ('T50_err_applied', models.TimeField(verbose_name='T50_err_applied')),
                ('sat_altitude', models.FloatField(verbose_name='sat_altitude')),
                ('ML_counts', models.FloatField(verbose_name='ML_counts')),
                ('ML_counts_err', models.FloatField(verbose_name='ML_counts_err')),
                ('ML_counts_err_applied', models.FloatField(verbose_name='ML_counts_err_applied')),
                ('event_type', models.IntegerField(verbose_name='event_type')),
                ('RA', models.FloatField(verbose_name='RA')),
                ('DEC', models.FloatField(verbose_name='DEC')),
                ('start_time_obs', models.DateTimeField(verbose_name='start_time_obs')),
                ('end_time_obs', models.DateTimeField(verbose_name='end_time_obs')),
                ('reliability', models.FloatField(verbose_name='reliability')),
            ],
        ),
    ]
