# Generated by Django 4.2.13 on 2024-06-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spadeapp', '0003_tgf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earthquake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sat_source', models.CharField(max_length=50, verbose_name='Source')),
                ('trigger_time', models.DateTimeField(verbose_name='trigger_time')),
                ('latitude', models.FloatField(verbose_name='latitude')),
                ('longitude', models.FloatField(verbose_name='longitude')),
                ('horizontal_err', models.FloatField(verbose_name='horizontal_err')),
                ('depth', models.FloatField(verbose_name='depth')),
                ('depth_err', models.FloatField(verbose_name='depth_err')),
                ('magnitude', models.FloatField(verbose_name='magnitude')),
                ('magnitude_err', models.FloatField(verbose_name='magnitude_err')),
                ('magType', models.CharField(max_length=4, verbose_name='Magnitude type')),
                ('nst', models.IntegerField(verbose_name='Nst')),
                ('magnst', models.IntegerField(verbose_name='Magnst')),
                ('gap', models.IntegerField(verbose_name='Gap')),
                ('dmin', models.FloatField(verbose_name='Dmin')),
                ('rms', models.FloatField(verbose_name='Rms')),
                ('net', models.CharField(max_length=2, verbose_name='Net')),
                ('identifier', models.CharField(max_length=20, verbose_name='Identifier')),
                ('place', models.CharField(max_length=50, verbose_name='Place')),
                ('type', models.CharField(max_length=20, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='GRB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sat_source', models.CharField(max_length=50, verbose_name='Source')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('trigger_time', models.DateTimeField(verbose_name='Trigger time')),
                ('RA', models.FloatField(verbose_name='RA')),
                ('DEC', models.FloatField(verbose_name='DEC')),
                ('T90', models.TimeField(verbose_name='T90 (s)')),
                ('geo_long', models.FloatField(verbose_name='Geo longitude (deg)')),
                ('geo_lat', models.FloatField(verbose_name='Geo latitude (deg)')),
                ('start_time_obs', models.TimeField(verbose_name='Start time observations (s)')),
                ('end_time_obs', models.TimeField(verbose_name='End time observations (s)')),
                ('reliability', models.FloatField(verbose_name='Reliability')),
                ('duration', models.IntegerField(verbose_name='Duration (s)')),
                ('type', models.IntegerField(verbose_name='Type')),
                ('sigma', models.FloatField(verbose_name='Sigma')),
                ('max_count', models.IntegerField(verbose_name='Max count')),
                ('fluence90err', models.FloatField(verbose_name='Fluence 90 error (kev)')),
                ('sec_peak_photon_flux', models.FloatField(verbose_name='1 sec peak photon flux')),
                ('photon_index', models.FloatField(verbose_name='Photon index')),
                ('photon_index_90err', models.FloatField(verbose_name='Photon index 90 error')),
                ('xrtRA', models.FloatField(verbose_name='xrtRA')),
                ('xrtDEC', models.FloatField(verbose_name='xrtDEC')),
                ('xrt_90radius', models.FloatField(verbose_name='xrt 90 radius error')),
                ('xrt_time_to_first_obs', models.TimeField(verbose_name='xrt time to first observation')),
                ('xrt_early_flux', models.FloatField(verbose_name='xrt early flux')),
                ('xrt_11h_flux_error', models.FloatField(verbose_name='xrt 11 hours flux error')),
                ('xrt_24h_flux_error', models.FloatField(verbose_name='xrt 24 hours flux error')),
                ('xrt_initial_temp_index', models.FloatField(verbose_name='xrt initial temporal index')),
                ('xrt_spectral_index', models.FloatField(verbose_name='xrt spectral index')),
                ('uvotRA', models.CharField(max_length=100, verbose_name='UVOT RA')),
                ('uvotDEC', models.CharField(max_length=100, verbose_name='UVOT DEC')),
                ('uvot_time_to_first_obs', models.CharField(max_length=100, verbose_name='UVOT time to first observation')),
                ('uvot_magnitude', models.CharField(max_length=100, verbose_name='UVOT magnitude')),
                ('uvot_magnitude_filter', models.CharField(max_length=100, verbose_name='UVOT magnitude filters')),
                ('other_obs_detects', models.CharField(max_length=100, verbose_name='Other objects detections')),
                ('redshift', models.CharField(max_length=100, verbose_name='Redshift')),
                ('host_galaxy', models.CharField(max_length=100, verbose_name='Host galaxy')),
                ('references', models.CharField(max_length=100, verbose_name='References')),
            ],
        ),
        migrations.CreateModel(
            name='SWE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sat_source', models.CharField(max_length=50, verbose_name='Source')),
                ('flux', models.CharField(max_length=5, verbose_name='Flux')),
                ('region', models.IntegerField(verbose_name='Region')),
                ('trigger_time', models.DateTimeField(verbose_name='Trigger time')),
                ('time_start_obs', models.DateTimeField(verbose_name='Time start observations')),
            ],
        ),
        migrations.AddField(
            model_name='tgf',
            name='sat_source',
            field=models.CharField(default='Fermi', max_length=50, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='GEO_lat',
            field=models.FloatField(verbose_name='Geo latitude'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='GEO_long',
            field=models.FloatField(verbose_name='Geo longitude'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='ML_counts',
            field=models.FloatField(verbose_name='ML counts'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='ML_counts_err',
            field=models.FloatField(verbose_name='ML counts error'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='ML_counts_err_applied',
            field=models.FloatField(verbose_name='ML counts error applied'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='T50_err',
            field=models.TimeField(verbose_name='T50 error'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='T50_err_applied',
            field=models.TimeField(verbose_name='T50 error applied'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='TGF_name',
            field=models.CharField(max_length=30, verbose_name='TGF name'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='end_time_obs',
            field=models.DateTimeField(verbose_name='End time observations'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='event_type',
            field=models.IntegerField(verbose_name='Event type'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='orbit',
            field=models.IntegerField(verbose_name='Orbit'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='reliability',
            field=models.FloatField(verbose_name='Reliability'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='sat_altitude',
            field=models.FloatField(verbose_name='Satellite altitude'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='start_time_obs',
            field=models.DateTimeField(verbose_name='Start time observations'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='trigger_time',
            field=models.DateTimeField(verbose_name='Trigger time'),
        ),
    ]
