# Generated by Django 4.2.13 on 2024-07-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spadeapp', '0003_alter_swe_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='grb',
            name='DEC',
            field=models.CharField(default='0', max_length=50, verbose_name='DEC'),
        ),
        migrations.AddField(
            model_name='grb',
            name='RA',
            field=models.CharField(default='0', max_length=50, verbose_name='RA'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='BAT_DEC',
            field=models.FloatField(verbose_name='BAT_DEC'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='BAT_RA',
            field=models.FloatField(verbose_name='BAT_RA'),
        ),
    ]
