# Generated by Django 4.2.13 on 2024-07-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spadeapp', '0004_grb_dec_grb_ra_alter_grb_bat_dec_alter_grb_bat_ra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplemodel',
            name='num',
            field=models.FloatField(),
        ),
    ]
