# Generated by Django 4.2.13 on 2024-07-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spadeapp', '0005_alter_samplemodel_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplemodel',
            name='num',
            field=models.CharField(max_length=10),
        ),
    ]
