# Generated by Django 4.2.13 on 2024-06-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spadeapp', '0005_earthquake_locationsource_earthquake_magsource_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grb',
            old_name='sec_peak_photon_flux',
            new_name='BAT_1sec_peak_photon_flux',
        ),
        migrations.RenameField(
            model_name='grb',
            old_name='DEC',
            new_name='BAT_DEC',
        ),
        migrations.RenameField(
            model_name='grb',
            old_name='RA',
            new_name='BAT_RA',
        ),
        migrations.RenameField(
            model_name='grb',
            old_name='fluence90err',
            new_name='BAT_fluence_90_err',
        ),
        migrations.RenameField(
            model_name='grb',
            old_name='photon_index',
            new_name='BAT_photon_index',
        ),
        migrations.RenameField(
            model_name='grb',
            old_name='photon_index_90err',
            new_name='BAT_photon_index_90_err',
        ),
        migrations.RenameField(
            model_name='grb',
            old_name='xrt_90radius',
            new_name='xrt_90_err',
        ),
        migrations.AddField(
            model_name='grb',
            name='BAT_1sec_peak_photon_flux_90_err',
            field=models.FloatField(default=0, verbose_name='1 sec peak photon flux 90 err'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grb',
            name='BAT_90_err',
            field=models.FloatField(default=0, verbose_name='Bat 90%/ error radius'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grb',
            name='BAT_fluence',
            field=models.FloatField(default=0, verbose_name='Bat fluence'),
            preserve_default=False,
        ),
    ]
