# Generated by Django 4.2.13 on 2024-06-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spadeapp', '0006_rename_sec_peak_photon_flux_grb_bat_1sec_peak_photon_flux_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grb',
            name='xrt_column_density',
            field=models.FloatField(default=0, verbose_name='Column density'),
            preserve_default=False,
        ),
    ]
