# Generated by Django 4.2.13 on 2024-07-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spadeapp', '0006_alter_samplemodel_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earthquake',
            name='depth',
            field=models.CharField(max_length=50, verbose_name='depth'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='depth_err',
            field=models.CharField(max_length=50, verbose_name='depth_err'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='dmin',
            field=models.CharField(max_length=50, verbose_name='Dmin'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='gap',
            field=models.IntegerField(max_length=50, verbose_name='Gap'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='horizontal_err',
            field=models.CharField(max_length=50, verbose_name='horizontal_err'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='latitude',
            field=models.CharField(max_length=50, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='longitude',
            field=models.CharField(max_length=50, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='magnitude',
            field=models.CharField(max_length=50, verbose_name='magnitude'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='magnitude_err',
            field=models.CharField(max_length=50, verbose_name='magnitude_err'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='magnst',
            field=models.IntegerField(max_length=50, verbose_name='Magnst'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='nst',
            field=models.IntegerField(max_length=50, verbose_name='Nst'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='rms',
            field=models.CharField(max_length=50, verbose_name='Rms'),
        ),
    ]
