# Generated by Django 4.2.13 on 2024-07-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spadeapp', '0007_alter_earthquake_depth_alter_earthquake_depth_err_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earthquake',
            name='gap',
            field=models.CharField(max_length=50, verbose_name='Gap'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='magnst',
            field=models.CharField(max_length=50, verbose_name='Magnst'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='nst',
            field=models.CharField(max_length=50, verbose_name='Nst'),
        ),
    ]
