# Generated by Django 4.2.13 on 2024-06-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spadeapp', '0008_grb_uvot_90_err'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplemodel',
            name='num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
