# Generated by Django 4.2.13 on 2024-07-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spadeapp', '0008_alter_earthquake_gap_alter_earthquake_magnst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earthquake',
            name='source',
        ),
        migrations.AddField(
            model_name='earthquake',
            name='status',
            field=models.CharField(default='0', max_length=50, verbose_name='Status'),
        ),
    ]
