# Generated by Django 4.2.13 on 2024-07-01 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spadeapp', '0009_remove_earthquake_source_earthquake_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earthquake',
            name='depth',
            field=models.FloatField(verbose_name='depth'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='depth_err',
            field=models.FloatField(verbose_name='depth_err'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='dmin',
            field=models.FloatField(max_length=50, verbose_name='Dmin'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='gap',
            field=models.FloatField(max_length=50, verbose_name='Gap'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='horizontal_err',
            field=models.FloatField(max_length=50, verbose_name='horizontal_err'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='latitude',
            field=models.FloatField(verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='longitude',
            field=models.FloatField(verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='magType',
            field=models.FloatField(max_length=4, verbose_name='Magnitude type'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='magnitude',
            field=models.FloatField(max_length=50, verbose_name='magnitude'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='magnitude_err',
            field=models.FloatField(verbose_name='magnitude_err'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='magnst',
            field=models.FloatField(verbose_name='Magnst'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='nst',
            field=models.FloatField(max_length=50, verbose_name='Nst'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='rms',
            field=models.FloatField(max_length=50, verbose_name='Rms'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='trigger_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 15, 20, 48, 377486, tzinfo=datetime.timezone.utc), verbose_name='trigger_time'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='end_time_obs',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 15, 20, 48, 381475, tzinfo=datetime.timezone.utc), verbose_name='End time observations (s)'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='start_time_obs',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 15, 20, 48, 381475, tzinfo=datetime.timezone.utc), verbose_name='Start time observations (s)'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='trigger_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 15, 20, 48, 381475, tzinfo=datetime.timezone.utc), verbose_name='Trigger time'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='xrt_time_to_first_obs',
            field=models.TimeField(max_length=50, verbose_name='xrt time to first observation'),
        ),
        migrations.AlterField(
            model_name='swe',
            name='time_end_obs',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 15, 20, 48, 380478, tzinfo=datetime.timezone.utc), verbose_name='Time end observations'),
        ),
        migrations.AlterField(
            model_name='swe',
            name='time_start_obs',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 15, 20, 48, 380478, tzinfo=datetime.timezone.utc), verbose_name='Time start observations'),
        ),
        migrations.AlterField(
            model_name='swe',
            name='trigger_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 15, 20, 48, 380478, tzinfo=datetime.timezone.utc), verbose_name='Trigger time'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='end_time_obs',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 15, 20, 48, 379480, tzinfo=datetime.timezone.utc), verbose_name='End time observations'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='start_time_obs',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 15, 20, 48, 379480, tzinfo=datetime.timezone.utc), verbose_name='Start time observations'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='trigger_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 15, 20, 48, 379480, tzinfo=datetime.timezone.utc), verbose_name='Trigger time'),
        ),
    ]
