# Generated by Django 4.2.13 on 2024-07-01 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spadeapp', '0017_alter_earthquake_magtype_alter_grb_end_time_obs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earthquake',
            name='depth_err',
            field=models.CharField(max_length=50, verbose_name='depth_err'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='dmin',
            field=models.CharField(max_length=50, verbose_name='Dmin'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='gap',
            field=models.CharField(max_length=50, verbose_name='Gap'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='horizontal_err',
            field=models.CharField(max_length=50, verbose_name='horizontal_err'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='magnitude_err',
            field=models.CharField(max_length=50, verbose_name='magnitude_err'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='magnst',
            field=models.CharField(max_length=50, verbose_name='Magnst'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='nst',
            field=models.CharField(max_length=50, verbose_name='Nst'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='rms',
            field=models.CharField(max_length=50, verbose_name='Rms'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='end_time_obs',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 16, 18, 48, 473379, tzinfo=datetime.timezone.utc), verbose_name='End time observations (s)'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='start_time_obs',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 16, 18, 48, 473379, tzinfo=datetime.timezone.utc), verbose_name='Start time observations (s)'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='trigger_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 16, 18, 48, 473379, tzinfo=datetime.timezone.utc), verbose_name='Trigger time'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='end_time_obs',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 16, 18, 48, 472382, tzinfo=datetime.timezone.utc), verbose_name='End time observations'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='orbit',
            field=models.FloatField(verbose_name='Orbit'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='start_time_obs',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 16, 18, 48, 472382, tzinfo=datetime.timezone.utc), verbose_name='Start time observations'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='trigger_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 16, 18, 48, 472382, tzinfo=datetime.timezone.utc), verbose_name='Trigger time'),
        ),
    ]
