# Generated by Django 4.2.13 on 2024-07-01 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spadeapp', '0018_alter_earthquake_depth_err_alter_earthquake_dmin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grb',
            name='end_time_obs',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 16, 20, 38, 215905, tzinfo=datetime.timezone.utc), verbose_name='End time observations (s)'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='start_time_obs',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 16, 20, 38, 215905, tzinfo=datetime.timezone.utc), verbose_name='Start time observations (s)'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='trigger_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 16, 20, 38, 215905, tzinfo=datetime.timezone.utc), verbose_name='Trigger time'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='T50',
            field=models.FloatField(verbose_name='T50'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='T50_err',
            field=models.FloatField(verbose_name='T50 error'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='T50_err_applied',
            field=models.FloatField(verbose_name='T50 error applied'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='end_time_obs',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 16, 20, 38, 213911, tzinfo=datetime.timezone.utc), verbose_name='End time observations'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='start_time_obs',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 16, 20, 38, 213911, tzinfo=datetime.timezone.utc), verbose_name='Start time observations'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='trigger_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 16, 20, 38, 213911, tzinfo=datetime.timezone.utc), verbose_name='Trigger time'),
        ),
    ]
