# Generated by Django 4.2.13 on 2024-07-01 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spadeapp', '0025_alter_grb_end_time_obs_alter_grb_start_time_obs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grb',
            name='end_time_obs',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 16, 33, 34, 438433, tzinfo=datetime.timezone.utc), verbose_name='End time observations (s)'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='start_time_obs',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 16, 33, 34, 437438, tzinfo=datetime.timezone.utc), verbose_name='Start time observations (s)'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='trigger_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 16, 33, 34, 437438, tzinfo=datetime.timezone.utc), verbose_name='Trigger time'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='GEO_lat',
            field=models.CharField(max_length=50, verbose_name='Geo latitude'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='GEO_long',
            field=models.CharField(max_length=50, verbose_name='Geo longitude'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='ML_counts',
            field=models.CharField(max_length=50, verbose_name='ML counts'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='ML_counts_err',
            field=models.CharField(max_length=50, verbose_name='ML counts error'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='T50',
            field=models.CharField(max_length=50, verbose_name='T50'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='T50_err',
            field=models.CharField(max_length=50, verbose_name='T50 error'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='event_type',
            field=models.CharField(max_length=50, verbose_name='Event type'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='normalised_duration',
            field=models.CharField(default='1', max_length=50, verbose_name='Normalised duration'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='orbit',
            field=models.CharField(max_length=50, verbose_name='Orbit'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='sat_altitude',
            field=models.CharField(max_length=50, verbose_name='Satellite altitude'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='trigger_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 16, 33, 34, 436439, tzinfo=datetime.timezone.utc), verbose_name='Trigger time'),
        ),
    ]
