# Generated by Django 4.2.13 on 2024-07-01 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spadeapp', '0029_alter_grb_end_time_obs_alter_grb_start_time_obs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grb',
            name='end_time_obs',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 18, 14, 24, 976491, tzinfo=datetime.timezone.utc), verbose_name='End time observations (s)'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='references',
            field=models.CharField(default='nd', max_length=100, verbose_name='References'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='start_time_obs',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 18, 14, 24, 976491, tzinfo=datetime.timezone.utc), verbose_name='Start time observations (s)'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='trigger_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 18, 14, 24, 976491, tzinfo=datetime.timezone.utc), verbose_name='Trigger time'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='trigger_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 18, 14, 24, 974497, tzinfo=datetime.timezone.utc), verbose_name='Trigger time'),
        ),
    ]
