# Generated by Django 4.2.13 on 2024-07-01 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spadeapp', '0031_alter_grb_end_time_obs_alter_grb_start_time_obs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grb',
            name='BAT_1sec_peak_photon_flux',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='BAT_1sec_peak_photon_flux_90_err',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='BAT_90_err',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='BAT_fluence_90_err',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='BAT_photon_index',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='BAT_photon_index_90_err',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='host_galaxy',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='other_obs_detects',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='redshift',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='references',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='uvotDEC',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='uvotRA',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='uvot_90_err',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='uvot_magnitude',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='uvot_magnitude_filter',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='uvot_time_to_first_obs',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='xrtDEC',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='xrtRA',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='xrt_11h_flux_error',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='xrt_24h_flux_error',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='xrt_90_err',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='xrt_column_density',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='xrt_early_flux',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='xrt_initial_temp_index',
        ),
        migrations.RemoveField(
            model_name='grb',
            name='xrt_time_to_first_obs',
        ),
        migrations.AddField(
            model_name='grb',
            name='BAT_T90',
            field=models.CharField(default='-', max_length=50, verbose_name='BAT_T90'),
        ),
        migrations.AddField(
            model_name='grb',
            name='normalised_duration',
            field=models.CharField(default='-', max_length=50, verbose_name='normalised_duration'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='BAT_DEC',
            field=models.CharField(max_length=50, verbose_name='BAT_DEC'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='BAT_RA',
            field=models.CharField(max_length=50, verbose_name='BAT_RA'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='BAT_fluence',
            field=models.CharField(max_length=50, verbose_name='Bat fluence'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='T90',
            field=models.CharField(max_length=50, verbose_name='T90 (s)'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='end_time_obs',
            field=models.CharField(max_length=50, verbose_name='End time observations (s)'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='start_time_obs',
            field=models.CharField(max_length=50, verbose_name='Start time observations (s)'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='trigger_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 19, 34, 54, 733159, tzinfo=datetime.timezone.utc), verbose_name='Trigger time'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='xrt_spectral_index',
            field=models.CharField(max_length=50, verbose_name='xrt spectral index'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='trigger_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 19, 34, 54, 732162, tzinfo=datetime.timezone.utc), verbose_name='Trigger time'),
        ),
    ]
