# Generated by Django 4.2.13 on 2024-07-01 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spadeapp', '0032_remove_grb_bat_1sec_peak_photon_flux_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grb',
            name='reliability',
            field=models.CharField(max_length=50, verbose_name='Reliability'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='trigger_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 19, 35, 48, 248119, tzinfo=datetime.timezone.utc), verbose_name='Trigger time'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='trigger_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 19, 35, 48, 247122, tzinfo=datetime.timezone.utc), verbose_name='Trigger time'),
        ),
    ]
