# Generated by Django 4.2.13 on 2024-07-01 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spadeapp', '0034_alter_grb_geo_lat_alter_grb_geo_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grb',
            name='max_count',
            field=models.CharField(max_length=50, verbose_name='Max count'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='sigma',
            field=models.FloatField(max_length=50, verbose_name='Sigma'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='trigger_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 19, 37, 41, 2965, tzinfo=datetime.timezone.utc), verbose_name='Trigger time'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='trigger_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 19, 37, 41, 1969, tzinfo=datetime.timezone.utc), verbose_name='Trigger time'),
        ),
    ]
