# Generated by Django 4.2.13 on 2024-07-01 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spadeapp', '0035_alter_grb_max_count_alter_grb_sigma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grb',
            name='sigma',
            field=models.CharField(max_length=50, verbose_name='Sigma'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='trigger_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 19, 38, 17, 150823, tzinfo=datetime.timezone.utc), verbose_name='Trigger time'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='trigger_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 19, 38, 17, 147831, tzinfo=datetime.timezone.utc), verbose_name='Trigger time'),
        ),
    ]
