# Generated by Django 4.2.13 on 2024-07-02 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spadeapp', '0036_alter_grb_sigma_alter_grb_trigger_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earthquake',
            name='trigger_time',
            field=models.DateTimeField(verbose_name='trigger_time'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='trigger_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 7, 52, 8, 508233, tzinfo=datetime.timezone.utc), verbose_name='Trigger time'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='trigger_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 7, 52, 8, 508233, tzinfo=datetime.timezone.utc), verbose_name='Trigger time'),
        ),
    ]
