# Generated by Django 4.2.13 on 2024-07-02 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spadeapp', '0039_swe_top_alter_earthquake_depth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earthquake',
            name='locationSource',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Location source'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='magSource',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Magnitude source'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='updated',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='BAT_T90',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='BAT_T90'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='DEC',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='DEC'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='RA',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='RA'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='trigger_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 2, 11, 0, 25, 962947, tzinfo=datetime.timezone.utc), verbose_name='Trigger time'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='normalised_duration',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Normalised duration'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='trigger_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 2, 11, 0, 25, 961959, tzinfo=datetime.timezone.utc), verbose_name='Trigger time'),
        ),
    ]
