# Generated by Django 5.0.6 on 2024-07-02 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spadeapp', '0041_alter_grb_trigger_time_alter_tgf_trigger_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grb',
            name='trigger_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 2, 16, 19, 26, 516454, tzinfo=datetime.timezone.utc), verbose_name='Trigger time'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='trigger_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 2, 16, 19, 26, 515933, tzinfo=datetime.timezone.utc), verbose_name='Trigger time'),
        ),
    ]
