# Generated by Django 5.0.6 on 2024-07-03 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spadeapp', '0043_alter_grb_trigger_time_alter_tgf_trigger_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='GMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='grb',
            name='trigger_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 3, 8, 23, 44, 824174, tzinfo=datetime.timezone.utc), verbose_name='Trigger time'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='trigger_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 3, 8, 23, 44, 823680, tzinfo=datetime.timezone.utc), verbose_name='Trigger time'),
        ),
    ]
