# Generated by Django 5.0.6 on 2024-07-03 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spadeapp', '0044_gms_alter_grb_trigger_time_alter_tgf_trigger_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='gms',
            name='field_magnitude_average',
            field=models.CharField(blank=True, max_length=10, verbose_name='field_magnitude_average(nt)'),
        ),
        migrations.AddField(
            model_name='gms',
            name='source',
            field=models.CharField(blank=True, max_length=10, verbose_name='source'),
        ),
        migrations.AddField(
            model_name='gms',
            name='speed',
            field=models.CharField(blank=True, max_length=10, verbose_name='speed'),
        ),
        migrations.AddField(
            model_name='gms',
            name='trigger_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 8, 37, 18, 730328, tzinfo=datetime.timezone.utc), verbose_name='trigger_time'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='trigger_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 3, 8, 37, 18, 729934, tzinfo=datetime.timezone.utc), verbose_name='Trigger time'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='trigger_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 3, 8, 37, 18, 729385, tzinfo=datetime.timezone.utc), verbose_name='Trigger time'),
        ),
    ]
