# Generated by Django 5.0.6 on 2024-07-03 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spadeapp', '0051_alter_gms_trigger_time_alter_grb_trigger_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gms',
            name='trigger_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 21, 49, 51, 606703, tzinfo=datetime.timezone.utc), verbose_name='trigger_time'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='trigger_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 3, 21, 49, 51, 606358, tzinfo=datetime.timezone.utc), verbose_name='Trigger time'),
        ),
        migrations.AlterField(
            model_name='tgf',
            name='trigger_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 3, 21, 49, 51, 605878, tzinfo=datetime.timezone.utc), verbose_name='Trigger time'),
        ),
    ]
